// Mirrors hn_reader: lib/src/rust/api/model.dart
// (generated by flutter_rust_bridge + freezed; one subclass per Rust enum variant).

// #region block-heading
sealed class Block with _$Block {
  const Block._();

  const factory Block.heading({
    required int level,
    required List<Inline> spans,
  }) = Block_Heading;
  // … Block_Paragraph, Block_Image, Block_Code, Block_Quote, Block_List
}
// #endregion block-heading
